# PyTorch Basic

PyTorch 기초 사용법

In [1]:
import numpy as np

import torch

In [8]:
nums = np.arange(9)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
type(nums)

torch.Tensor

In [11]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [12]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [14]:
randoms = torch.rand((3, 3)) # zeros, ones
randoms

tensor([[0.2852, 0.2418, 0.3361],
        [0.5269, 0.8632, 0.9118],
        [0.5510, 0.0885, 0.2725]])

In [15]:
torch.zeros_like(randoms)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
nums.size()

torch.Size([9])

# Operations

PyTorch로 수학연산

In [19]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [22]:
nums = nums.reshape(3,3)

nums += nums
nums

tensor([[ 0,  4,  8],
        [12, 16, 20],
        [24, 28, 32]])

In [24]:
nums = torch.add(nums, 10) 
nums

tensor([[10, 14, 18],
        [22, 26, 30],
        [34, 38, 42]])

In [25]:
nums.numpy()

array([[10, 14, 18],
       [22, 26, 30],
       [34, 38, 42]], dtype=int64)

## View

In [26]:
range_nums = torch.arange(9).reshape(3,3)
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [27]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
range_nums.view(1,9).shape

torch.Size([1, 9])

## Compile

numpy를 torch tensor로 불러오기

In [31]:
arr = np.array([1, 1, 1])

arr_torch = torch.from_numpy(arr)
type(arr_torch)

torch.Tensor

In [32]:
arr_torch.float()

tensor([1., 1., 1.])

In [33]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [35]:
arr_torch.to(device)

tensor([1, 1, 1], dtype=torch.int32)

# AutoGrad

In [36]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [37]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [38]:
print(y.grad_fn)

In [39]:
z = y * y * 3
out = z.mean()

In [40]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [41]:
out.backward()

In [42]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [43]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [45]:
# test 할 때
with torch.no_grad():
    print((x ** 2).requires_grad)

False
